version: '3'
services:
  credit_worthiness:
    env_file: .env
    container_name: credit_worthiness
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      USERNAME: ${USERNAME}
      PASSWORD: ${PASSWORD}